[tracker]
type = "GitHub"
url = "https://github.com/kevgo/co-bot/issues"
human = "kevgo"
token_source = "git config git-town.github-token"  # shell script that prints the tracker token

[git]
# shell command to create the Git workspace
create-workspace = "git worktree add ../{{ticket.id}}-{{ticket.title}} && cd ../{{ticket.id}}-{{ticket.title}}"

# shell command to create a Git branch for the ticket
create-branch = "git town hack {{branch}}"

# shell command to commit the changes that the AI created
commit-message = "{{ticket.title}} part {{iteration}}"

# shell command to cleanup a Git branch that was shipped
cleanup-branch = "git town sync --all"

# shell command to cleanup the Git workspace
cleanup-workspace = "git worktree remove ../{{ticket.id}}-{{ticket.title}}"

[code]

# commands to test changes made by the AI
tests = [
  "make build",
  "make unit",
  "make lint",
  "make cuke"
]
