[tracker]
type = "GitHub"
url = "https://github.com/kevgo/co-bot/issues"
human = "kevgo"
token-source = "git config git-town.github-token"  # shell script that prints the tracker token

git.branch.name = "{{ticket.id}}-{{ticket.title}}"  # name of the Git branch to create
git.branch.create = "git town hack {{git.branch.name}}"      # shell command to create a Git branch for the ticket
git.branch.cleanup = "git town sync --all"          # shell command to cleanup a Git branch that was shipped

git.workspace.path = "../{{git.branch.name}}"                                         # can be an absolute path, or relative to the directory in which co-bot runs
git.workspace.create = "git worktree add {{git.workspace.path}} {{git.branch.name}}"  # shell command to create the Git workspace
git.workspace.cleanup = "git worktree remove {{git.workspace.path}}"                  # shell command to cleanup the Git workspace

git.commit.message = "{{ticket.title}} part {{iteration}}"  # shell command to commit the changes that the AI created

[code]

# commands to test changes made by the AI
tests = [
  "make build",
  "make unit",
  "make lint",
  "make cuke"
]
